services:
  kicki-back:
    container_name: kicki-back
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
    
  kicki-front:
    container_name: kicki-front
    build:
      context: .
      dockerfile: client/Dockerfile.prod
    ports:
      - "3002:3002"
    depends_on:
      - kicki-back
    restart: unless-stopped